[package]
name = "openwraw-py"
description = "Python bindings for the OpenWRaw Waters MassLynx RAW reader."
readme = "../../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
name = "openwraw"
crate-type = ["cdylib"]

[lints.rust]
unsafe_code = "forbid"

[dependencies]
openwraw.workspace = true
pyo3 = { workspace = true }
