[workspace]
resolver = "2"
members = ["crates/openwraw", "crates/openwraw-cli", "crates/openwraw-py"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Nathan Riley"]
license = "MIT"
repository = "https://github.com/NathanRiley/OpenWRaw"

[workspace.dependencies]
openwraw = { path = "crates/openwraw" }
pyo3 = { version = "0.28.3", features = ["extension-module"] }
