[package]
name = "openwraw-cli"
description = "Command-line tool for inspecting and converting Waters MassLynx RAW directories."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
openwraw.workspace = true
